olympic_list = [
    {
        'Year': 1988,
        'Athlete Name': 'Julius Kariuki',
        'Age': 27,
        'Sex': 'Male',
        'Height(in cm)': 175,
        'Weight': 63,
        'Medal': 1,
        'Medal_Type': 'Gold',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Sheol, South Korea',
        'Time(in hrs)': 2.13,
        'Distance(in km)': 42.195
    },
    {
        'Year': 1988,
        'Athlete Name': 'Douglas Wakiihuri',
        'Age': 28,
        'Sex': 'Male',
        'Height(in cm)': 172,
        'Weight': 62,
        'Medal': 1,
        'Medal_Type': 'Silver',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Sheol, South Korea',
        'Time(in hrs)': 2.16,
        'Distance(in km)': 42.195
    },
    {
        'Year': 2000,
        'Athlete Name': 'Tegla Loroupe',
        'Age': 27,
        'Sex': 'Female',
        'Height(in cm)': 165,
        'Weight': 48,
        'Medal': 1,
        'Medal_Type': 'Bronze',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Sydney,Australia',
        'Time(in hrs)': 2.44,
        'Distance(in km)': 42.195
    },
    {
        'Year': 2004,
        'Athlete Name': 'Catherine Ndereba',
        'Age': 32,
        'Sex': 'Female',
        'Height(in cm)': 158,
        'Weight': 50,
        'Medal': 1,
        'Medal_Type': 'Silver',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Athens, Greece',
        'Time(in hrs)': 2.40,
        'Distance(in km)': 42.195
    },
    {
        'Year': 2008,
        'Athlete Name': 'Pamela Jelimo',
        'Age': 18,
        'Sex': 'Female',
        'Height(in cm)': 165,
        'Weight': 50,
        'Medal': 1,
        'Medal_Type': 'Gold',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Beijing, China',
        'Time(in hrs)': 1.92,
        'Distance(in km)': 0.8
    },
    {
        'Year': 2008,
        'Athlete Name': 'Catherine Ndereba',
        'Age': 36,
        'Sex': 'Female',
        'Height(in cm)': 158,
        'Weight': 50,
        'Medal': 1,
        'Medal_Type': 'Silver',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Beijing, China',
        'Time(in hrs)': 2.45,
        'Distance(in km)': 42.195
    },
    {
        'Year': 2016,
        'Athlete Name': 'Eliud Kipchoge',
        'Age': 31,
        'Sex': 'Male',
        'Height(in cm)': 167,
        'Weight': 52,
        'Medal': 1,
        'Medal_Type': 'Gold',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Brazil',
        'Time(in hrs)': 2.13,
        'Distance(in km)': 42.195
    },
    {
        'Year': 2020,
        'Athlete Name': 'Eliud Kipchoge',
        'Age': 36,
        'Sex': 'Male',
        'Height(in cm)': 167,
        'Weight': 52,
        'Medal': 1,
        'Medal_Type': 'Gold',
        'Sport': 'Marathon',
        'Country': 'Kenya',
        'Event': 'Tokyo, Japan',
        'Time(in hrs)': 2.13,
        'Distance(in km)': 42.195
    }
]
